name: Dentist Appointment Booking CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
        os: [ windows-latest, linux-latest, macos-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_COOKIE_KEY_1: ${{ secrets.COOKIE_KEY_1 }}
          envkey_COOKIE_KEY_2: ${{ secrets.COOKIE_KEY_2 }}
          envkey_COOKIE_KEY_3: ${{ secrets.COOKIE_KEY_3 }}
          envkey_ORIGIN: ${{ secrets.ORIGIN }}
          envkey_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          envkey_OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          fail_on_empty: true
      - name: Checkout Git
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm install
      - name: Compile to JavaScript
        run: npm run build
      - name: Run tests
        run: npm test